{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reforge.fullname" . }}-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reforge.fullname" . }}-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [control, docs, auth-server]
  policyTypes: [Ingress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9000
{{- if .Values.postgresql.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reforge.fullname" . }}-postgresql
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ .Release.Name }}
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values: [control, auth-server, auth-worker]
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
{{- end }}
