\getenv authentik_password AUTHENTIK_DATABASE_PASSWORD
SELECT format('CREATE ROLE authentik WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L', :'authentik_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authentik')
\gexec
SELECT format('ALTER ROLE authentik WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD %L', :'authentik_password')
\gexec
SELECT 'CREATE DATABASE authentik OWNER authentik'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'authentik')
\gexec
